// Tests for UserDialog — the admin form for creating and editing team members.
// Key business rules:
//   - New users get a temporary password that is auto-generated by the backend;
//     the admin may optionally pre-set one via the dialog's password field
//   - Employees and team leads require at least one approver (non-admin users
//     must always have someone to review their time/absence requests)
//   - The admin role can optionally disable time tracking (tracks_time=false);
//     requires double-confirmation because it changes the account's data scope
//   - Approver list only shows active team leads and admins

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { mount, unmount } from "svelte";
import UserDialog from "./UserDialog.svelte";
import { settings } from "../stores.js";
import { setLanguage } from "../i18n.js";

const apiMock = vi.hoisted(() => vi.fn());

const leaveAccountDefinitions = [
  {
    category_id: 1,
    category_name: "Vacation",
    color: "#3b82f6",
    default_base_days: 30,
    active: true,
    carryover_expiry: "03-31",
  },
  {
    category_id: 8,
    category_name: "Education leave",
    color: "#14b8a6",
    default_base_days: 5,
    active: true,
    carryover_expiry: "01-31",
  },
];

function userLeaveAccounts() {
  const currentYear = new Date().getFullYear();
  return leaveAccountDefinitions.map((account) => ({
    category_id: account.category_id,
    category_name: account.category_name,
    color: account.color,
    active: account.active,
    base_days: account.default_base_days,
    current_year: currentYear,
    current_year_days: account.default_base_days,
    next_year: currentYear + 1,
    next_year_days: account.default_base_days,
  }));
}

vi.mock("svelte", async () => {
  return await import("../../node_modules/svelte/src/index-client.js");
});

vi.mock("../api.js", () => ({
  api: apiMock,
}));

vi.mock("../confirm.js", () => ({
  confirmDialog: vi.fn().mockResolvedValue(true),
}));

async function settle() {
  await Promise.resolve();
  await new Promise((resolve) => setTimeout(resolve, 0));
  await Promise.resolve();
}

async function waitForText(target, text, timeout = 5000) {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    if (target.textContent?.includes(text)) return;
    await new Promise((r) => setTimeout(r, 25));
  }
  throw new Error(`Text not found: "${text}"`);
}

describe("UserDialog", () => {
  let target;
  let component;
  let originalShowModal;

  beforeEach(() => {
    target = document.createElement("div");
    document.body.appendChild(target);
    setLanguage("en");
    settings.set({ ui_language: "en", time_format: "24h", timezone: "UTC" });

    // Default API: return an empty approver list and no settings overrides
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/settings")
        return {
          default_weekly_hours: 39,
          smtp_enabled: false,
        };
      if (path === "/leave-accounts") return leaveAccountDefinitions;
      if (path === "/users/7/leave-accounts") return userLeaveAccounts();
      return [];
    });

    originalShowModal = HTMLDialogElement.prototype.showModal;
    HTMLDialogElement.prototype.showModal = function () {
      this.setAttribute("open", "");
    };
  });

  afterEach(() => {
    if (component) {
      unmount(component);
      component = null;
    }
    target.remove();
    HTMLDialogElement.prototype.showModal = originalShowModal;
  });

  it("renders 'Add User' title for a new user", async () => {
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: {}, onClose },
    });
    await waitForText(target, "Add User");
  });

  it("shows 'Edit User' in the dialog title for an existing user", async () => {
    // The title switches from 'Add User' to 'Edit User' so admins
    // immediately know they are modifying, not creating, an account.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/users/7/leave-accounts") return userLeaveAccounts();
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          approver_ids: [],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit User");
  });

  it("shows a validation error when employee has no approver selected", async () => {
    // Backend enforces that every non-admin user has at least one approver.
    // The frontend must validate this before submitting to give the admin
    // an immediate error instead of waiting for a network roundtrip.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add User");

    const saveBtn = [...target.querySelectorAll("button")].find(
      (b) => b.textContent.includes("Save") || b.textContent.includes("Add"),
    );
    saveBtn?.click();
    await settle();
    await settle();

    expect(target.textContent).toContain("approver");
  });

  it("renders password fields for a new user", async () => {
    // The backend auto-generates a temporary password, but the admin can
    // optionally pre-set one. The dialog shows the password and confirm
    // fields for new users so this optional override is always available.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: {}, onClose },
    });
    await waitForText(target, "Add User");

    const passwordFields = target.querySelectorAll('input[type="password"]');
    expect(passwordFields.length).toBeGreaterThanOrEqual(1);
  });

  it("fetches leave accounts when editing an existing user", async () => {
    // Entitlements are stored separately from the user record. The form must
    // load every account so the admin can edit the base and two year values.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/users/7/leave-accounts") return userLeaveAccounts();
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          approver_ids: [],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit User");
    await settle();

    const leaveAccountsCall = apiMock.mock.calls.find(
      ([path]) => typeof path === "string" && path.includes("/leave-accounts"),
    );
    expect(leaveAccountsCall).toBeTruthy();
    expect(target.textContent).toContain("Education leave");
  });

  it("shows the optional hire date field with its explanatory helper text", async () => {
    // hire_date lets admins anchor leave proration on a real employment start
    // that predates the user's Zerf start_date — e.g. when onboarding someone
    // who already worked the full year before the team adopted Zerf. The field
    // must be visible (and explained) for both new and existing users.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: {}, onClose },
    });
    await waitForText(target, "Add User");

    expect(target.textContent).toContain("Hire date");
    expect(target.textContent).toContain(
      "Used to calculate the prorated leave-account entitlement",
    );
  });

  it("shows a clear button for the hire date only while it has a value", async () => {
    // The DatePicker itself has no built-in way to clear back to empty (which
    // is what reverts proration to the start_date fallback on the backend), so
    // the dialog adds a small icon button — visible only when there is
    // something to clear.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/users/7/leave-accounts") return userLeaveAccounts();
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          hire_date: "2018-03-01",
          approver_ids: [],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit User");
    await settle();

    const findClearBtn = () =>
      [...target.querySelectorAll("button")].find(
        (b) => b.getAttribute("title") === "Clear",
      );

    expect(findClearBtn()).toBeTruthy();

    findClearBtn().click();
    await settle();

    expect(findClearBtn()).toBeFalsy();
  });

  it("defaults to every category enabled for a new user and sends them on save", async () => {
    // Matches the backend default ("all existing categories") so the admin
    // sees an explicit, pre-checked list rather than an empty one they'd
    // have to fill in by hand.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users")
        return [
          {
            id: 5,
            first_name: "Lara",
            last_name: "Lead",
            role: "team_lead",
            active: true,
          },
        ];
      if (path === "/settings")
        return {
          default_weekly_hours: 39,
          smtp_enabled: false,
        };
      if (path === "/leave-accounts") return leaveAccountDefinitions;
      if (path === "/categories/all")
        return [
          { id: 1, name: "Core Duties" },
          { id: 2, name: "Training" },
        ];
      if (path === "/absence-categories/all")
        return [{ id: 10, name: "Vacation" }];
      return { temporary_password: "x" };
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add User");
    await waitForText(target, "Education leave");

    expect(target.textContent).toContain("Core Duties");
    expect(target.textContent).toContain("Vacation");
    const checkboxes = target.querySelectorAll(
      'input[type="checkbox"][value="1"], input[type="checkbox"][value="2"], input[type="checkbox"][value="10"]',
    );
    expect(checkboxes.length).toBe(3);
    checkboxes.forEach((cb) => expect(cb.checked).toBe(true));

    // Select an approver (required for employees) and uncheck "Training".
    const approverCheckbox = [
      ...target.querySelectorAll('input[type="checkbox"]'),
    ].find((cb) => cb.value === "5");
    approverCheckbox.click();
    const trainingCheckbox = [
      ...target.querySelectorAll('input[type="checkbox"]'),
    ].find((cb) => cb.value === "2");
    trainingCheckbox.click();
    await settle();

    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Add"),
    );
    saveBtn?.click();
    await settle();

    const postCall = apiMock.mock.calls.find(
      ([path, opts]) => path === "/users" && opts?.method === "POST",
    );
    expect(postCall).toBeTruthy();
    expect(postCall[1].body.category_ids).toEqual([1]);
    expect(postCall[1].body.absence_category_ids).toEqual([10]);
    expect(postCall[1].body.leave_accounts).toEqual([
      {
        category_id: 1,
        base_days: 30,
        current_year_days: 30,
        next_year_days: 30,
      },
      {
        category_id: 8,
        base_days: 5,
        current_year_days: 5,
        next_year_days: 5,
      },
    ]);
  });

  it("sends the weekdays the admin ticked, not a count", async () => {
    // Naming the days is the whole point: a contract that works Tuesday to
    // Friday must be able to say so, or its Monday is charged as leave while
    // its Friday costs nothing. Before this the form offered only "how many",
    // and the days were guessed by counting up from Monday.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users")
        return [
          {
            id: 5,
            first_name: "Lara",
            last_name: "Lead",
            role: "team_lead",
            active: true,
          },
        ];
      if (path === "/settings")
        return { default_weekly_hours: 39, smtp_enabled: false };
      if (path === "/leave-accounts") return leaveAccountDefinitions;
      if (path === "/categories/all") return [];
      if (path === "/absence-categories/all") return [];
      return { temporary_password: "x" };
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add User");
    await waitForText(target, "Education leave");

    // A new contract starts out Monday to Friday.
    const dayBoxes = [...target.querySelectorAll("input[data-weekday]")];
    expect(dayBoxes.length).toBe(5);
    expect(dayBoxes.every((box) => box.checked)).toBe(true);

    // Turn it into a Tuesday-to-Friday contract.
    dayBoxes[0].click();
    const approverCheckbox = [
      ...target.querySelectorAll('input[type="checkbox"]'),
    ].find((cb) => cb.value === "5");
    approverCheckbox.click();
    await settle();

    // Calls from earlier tests share this mock, so look at what this save sent.
    apiMock.mockClear();
    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Add"),
    );
    saveBtn?.click();
    await settle();

    const postCall = apiMock.mock.calls.find(
      ([path, opts]) => path === "/users" && opts?.method === "POST",
    );
    expect(postCall).toBeTruthy();
    expect(postCall[1].body.work_weekdays).toEqual([2, 3, 4, 5]);
    expect(postCall[1].body.workdays_per_week).toBeUndefined();
  });

  it("refuses a contract with no working day at all", async () => {
    apiMock.mockImplementation(async (path) => {
      if (path === "/users")
        return [
          {
            id: 5,
            first_name: "Lara",
            last_name: "Lead",
            role: "team_lead",
            active: true,
          },
        ];
      if (path === "/settings")
        return { default_weekly_hours: 39, smtp_enabled: false };
      if (path === "/leave-accounts") return leaveAccountDefinitions;
      if (path === "/categories/all") return [];
      if (path === "/absence-categories/all") return [];
      return { temporary_password: "x" };
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add User");
    await waitForText(target, "Education leave");

    for (const box of target.querySelectorAll("input[data-weekday]")) {
      box.click();
    }
    const approverCheckbox = [
      ...target.querySelectorAll('input[type="checkbox"]'),
    ].find((cb) => cb.value === "5");
    approverCheckbox.click();
    await settle();

    apiMock.mockClear();
    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Add"),
    );
    saveBtn?.click();
    await settle();

    expect(target.querySelector(".error-text")?.textContent).toContain(
      "at least one weekday",
    );
    expect(apiMock.mock.calls.some(([, opts]) => opts?.method === "POST")).toBe(
      false,
    );
  });

  it("sets all leave accounts to zero for assistants and restores them after switching back", async () => {
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Education leave");

    const roleSelect = target.querySelector("#user-role");
    roleSelect.value = "assistant";
    roleSelect.dispatchEvent(new Event("change", { bubbles: true }));
    await settle();

    expect(target.querySelector("#leave-account-1-base").value).toBe("0");
    expect(target.querySelector("#leave-account-8-current").value).toBe("0");

    roleSelect.value = "employee";
    roleSelect.dispatchEvent(new Event("change", { bubbles: true }));
    await settle();

    expect(target.querySelector("#leave-account-1-base").value).toBe("30");
    expect(target.querySelector("#leave-account-8-current").value).toBe("5");
  });

  it("hides weekly hours, workdays, and the carry-in balance for assistants", async () => {
    // Assistants have no work target and no flextime account, so all three
    // fields are meaningless for their role and would only confuse the admin.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "assistant" }, onClose },
    });
    await waitForText(target, "Add User");
    await settle();

    expect(target.textContent).not.toContain("Weekly hours");
    expect(target.textContent).not.toContain("Workdays per week");
    expect(target.querySelector("#user-opening-balance")).toBeNull();
  });

  it("asks for the carry-in flextime balance when creating an employee", async () => {
    // The value is still collected at account creation — it just becomes a
    // dated ledger booking rather than an editable profile setting.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add User");
    await settle();

    expect(target.querySelector("#user-opening-balance")).not.toBeNull();
  });

  it("does not offer the carry-in balance when editing an existing user", async () => {
    // This is the whole point of the change: editing that number used to
    // rewrite every flextime balance ever reported for the person. The field
    // is gone and the admin is pointed at the flextime account instead.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/users/7/leave-accounts") return userLeaveAccounts();
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          approver_ids: [],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit User");
    await settle();

    expect(target.querySelector("#user-opening-balance")).toBeNull();
    expect(target.textContent).toContain("flextime account");
  });

  it("omits the carry-in balance from the create payload for a pure admin", async () => {
    // A pure-admin account (tracks_time=false) has no flextime ledger, so
    // there is nothing to book a carry-in balance into.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: { role: "admin", tracks_time: false },
        onClose,
      },
    });
    await waitForText(target, "Add User");
    await settle();

    expect(target.querySelector("#user-opening-balance")).toBeNull();

    target.querySelector("#user-first-name").value = "Pat";
    target
      .querySelector("#user-first-name")
      .dispatchEvent(new Event("input", { bubbles: true }));
    target.querySelector("#user-last-name").value = "Pureadmin";
    target
      .querySelector("#user-last-name")
      .dispatchEvent(new Event("input", { bubbles: true }));
    target.querySelector("#user-email").value = "pat@example.com";
    target
      .querySelector("#user-email")
      .dispatchEvent(new Event("input", { bubbles: true }));
    await settle();

    apiMock.mockClear();
    apiMock.mockResolvedValue({ temporary_password: "Temp!12345678" });
    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Add User"),
    );
    saveBtn?.click();
    await settle();
    await settle();

    const createCall = apiMock.mock.calls.find(
      (call) => call[0] === "/users" && call[1]?.method === "POST",
    );
    expect(createCall).toBeTruthy();
    expect(createCall[1].body).not.toHaveProperty(
      "flextime_opening_balance_min",
    );
    expect(createCall[1].body).not.toHaveProperty("overtime_start_balance_min");
  });

  it("hides the technical-error-notification opt-in for non-admin roles", async () => {
    // The opt-in only makes sense for admins, so it must not appear for employees.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add User");
    await settle();

    expect(target.textContent).not.toContain(
      "Receives notifications about technical system errors",
    );
  });

  it("offers the technical-error-notification opt-in for admins", async () => {
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "admin" }, onClose },
    });
    await waitForText(target, "Add User");
    await settle();

    expect(target.textContent).toContain(
      "Receives notifications about technical system errors",
    );
  });

  it("only sends category_ids/absence_category_ids on create, never on edit", async () => {
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/users/7/leave-accounts") return userLeaveAccounts();
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          approver_ids: [5],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit User");
    await settle();

    expect(target.textContent).not.toContain("Time Categories");
    expect(target.textContent).not.toContain("Absence Categories");

    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Save"),
    );
    saveBtn?.click();
    await settle();

    const putCall = apiMock.mock.calls.find(
      ([path, opts]) => path === "/users/7" && opts?.method === "PUT",
    );
    expect(putCall).toBeTruthy();
    expect(putCall[1].body).not.toHaveProperty("category_ids");
    expect(putCall[1].body).not.toHaveProperty("absence_category_ids");
  });
});
