// Tests for UserDialog — the admin form for creating and editing team members.
// Key business rules:
//   - New users get a temporary password that is auto-generated by the backend;
//     the admin may optionally pre-set one via the dialog's password field
//   - Employees and team leads require at least one approver (non-admin users
//     must always have someone to review their time/absence requests)
//   - The admin role can optionally disable time tracking (tracks_time=false);
//     requires double-confirmation because it changes the account's data scope
//   - Approver list only shows active team leads and admins

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { mount, unmount } from "svelte";
import UserDialog from "./UserDialog.svelte";
import { settings } from "../stores.js";
import { setLanguage } from "../i18n.js";

const apiMock = vi.hoisted(() => vi.fn());

vi.mock("svelte", async () => {
  return await import("../../node_modules/svelte/src/index-client.js");
});

vi.mock("../api.js", () => ({
  api: apiMock,
}));

vi.mock("../confirm.js", () => ({
  confirmDialog: vi.fn().mockResolvedValue(true),
}));

async function settle() {
  await Promise.resolve();
  await new Promise((resolve) => setTimeout(resolve, 0));
  await Promise.resolve();
}

async function waitForText(target, text, timeout = 5000) {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    if (target.textContent?.includes(text)) return;
    await new Promise((r) => setTimeout(r, 25));
  }
  throw new Error(`Text not found: "${text}"`);
}

describe("UserDialog", () => {
  let target;
  let component;
  let originalShowModal;

  beforeEach(() => {
    target = document.createElement("div");
    document.body.appendChild(target);
    setLanguage("en");
    settings.set({ ui_language: "en", time_format: "24h", timezone: "UTC" });

    // Default API: return an empty approver list and no settings overrides
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/settings")
        return { default_weekly_hours: 39, default_annual_leave_days: 30, smtp_enabled: false };
      return [];
    });

    originalShowModal = HTMLDialogElement.prototype.showModal;
    HTMLDialogElement.prototype.showModal = function () {
      this.setAttribute("open", "");
    };
  });

  afterEach(() => {
    if (component) { unmount(component); component = null; }
    target.remove();
    HTMLDialogElement.prototype.showModal = originalShowModal;
  });

  it("renders 'Add Member' title for a new user", async () => {
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: {}, onClose },
    });
    await waitForText(target, "Add Member");
  });

  it("shows 'Edit Member' in the dialog title for an existing user", async () => {
    // The title switches from 'Add Member' to 'Edit Member' so admins
    // immediately know they are modifying, not creating, an account.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path.endsWith("/leave-days")) return [];
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          approver_ids: [],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit Member");
  });

  it("shows a validation error when employee has no approver selected", async () => {
    // Backend enforces that every non-admin user has at least one approver.
    // The frontend must validate this before submitting to give the admin
    // an immediate error instead of waiting for a network roundtrip.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add Member");

    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Save") || b.textContent.includes("Add")
    );
    saveBtn?.click();
    await settle();
    await settle();

    expect(target.textContent).toContain("approver");
  });

  it("renders password fields for a new user", async () => {
    // The backend auto-generates a temporary password, but the admin can
    // optionally pre-set one. The dialog shows the password and confirm
    // fields for new users so this optional override is always available.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: {}, onClose },
    });
    await waitForText(target, "Add Member");

    const passwordFields = target.querySelectorAll('input[type="password"]');
    expect(passwordFields.length).toBeGreaterThanOrEqual(1);
  });

  it("fetches leave days when editing an existing user", async () => {
    // Leave days are stored separately from the user record. The form must
    // load them so the admin can see and update this year's and next year's entitlement.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path === "/users/7/leave-days")
        return [{ year: new Date().getFullYear(), days: 25 }];
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          approver_ids: [],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit Member");
    await settle();

    const leaveDaysCall = apiMock.mock.calls.find(
      ([path]) => typeof path === "string" && path.includes("/leave-days")
    );
    expect(leaveDaysCall).toBeTruthy();
  });

  it("shows the optional hire date field with its explanatory helper text", async () => {
    // hire_date lets admins anchor leave proration on a real employment start
    // that predates the user's Zerf start_date — e.g. when onboarding someone
    // who already worked the full year before the team adopted Zerf. The field
    // must be visible (and explained) for both new and existing users.
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: {}, onClose },
    });
    await waitForText(target, "Add Member");

    expect(target.textContent).toContain("Hire date");
    expect(target.textContent).toContain(
      "Used to calculate the prorated annual leave entitlement"
    );
  });

  it("shows a clear button for the hire date only while it has a value", async () => {
    // The DatePicker itself has no built-in way to clear back to empty (which
    // is what reverts proration to the start_date fallback on the backend), so
    // the dialog adds a small icon button — visible only when there is
    // something to clear.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path.endsWith("/leave-days")) return [];
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          hire_date: "2018-03-01",
          approver_ids: [],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit Member");
    await settle();

    const findClearBtn = () =>
      [...target.querySelectorAll("button")].find(
        (b) => b.getAttribute("title") === "Clear"
      );

    expect(findClearBtn()).toBeTruthy();

    findClearBtn().click();
    await settle();

    expect(findClearBtn()).toBeFalsy();
  });

  it("defaults to every category enabled for a new user and sends them on save", async () => {
    // Matches the backend default ("all existing categories") so the admin
    // sees an explicit, pre-checked list rather than an empty one they'd
    // have to fill in by hand.
    apiMock.mockImplementation(async (path) => {
      if (path === "/users")
        return [{ id: 5, first_name: "Lara", last_name: "Lead", role: "team_lead", active: true }];
      if (path === "/settings")
        return { default_weekly_hours: 39, default_annual_leave_days: 30, smtp_enabled: false };
      if (path === "/categories/all")
        return [
          { id: 1, name: "Core Duties" },
          { id: 2, name: "Training" },
        ];
      if (path === "/absence-categories/all")
        return [{ id: 10, name: "Vacation" }];
      return { temporary_password: "x" };
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: { template: { role: "employee" }, onClose },
    });
    await waitForText(target, "Add Member");
    await settle();

    expect(target.textContent).toContain("Core Duties");
    expect(target.textContent).toContain("Vacation");
    const checkboxes = target.querySelectorAll(
      'input[type="checkbox"][value="1"], input[type="checkbox"][value="2"], input[type="checkbox"][value="10"]',
    );
    expect(checkboxes.length).toBe(3);
    checkboxes.forEach((cb) => expect(cb.checked).toBe(true));

    // Select an approver (required for employees) and uncheck "Training".
    const approverCheckbox = [...target.querySelectorAll('input[type="checkbox"]')].find(
      (cb) => cb.value === "5",
    );
    approverCheckbox.click();
    const trainingCheckbox = [...target.querySelectorAll('input[type="checkbox"]')].find(
      (cb) => cb.value === "2",
    );
    trainingCheckbox.click();
    await settle();

    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Add"),
    );
    saveBtn?.click();
    await settle();

    const postCall = apiMock.mock.calls.find(
      ([path, opts]) => path === "/users" && opts?.method === "POST",
    );
    expect(postCall).toBeTruthy();
    expect(postCall[1].body.category_ids).toEqual([1]);
    expect(postCall[1].body.absence_category_ids).toEqual([10]);
  });

  it("only sends category_ids/absence_category_ids on create, never on edit", async () => {
    apiMock.mockImplementation(async (path) => {
      if (path === "/users") return [];
      if (path.endsWith("/leave-days")) return [];
      return {};
    });
    const onClose = vi.fn();
    component = mount(UserDialog, {
      target,
      props: {
        template: {
          id: 7,
          first_name: "Grace",
          last_name: "Green",
          role: "employee",
          email: "grace@example.com",
          weekly_hours: 40,
          workdays_per_week: 5,
          start_date: "2023-01-01",
          approver_ids: [5],
          active: true,
          tracks_time: true,
        },
        onClose,
      },
    });
    await waitForText(target, "Edit Member");
    await settle();

    expect(target.textContent).not.toContain("Time Categories");
    expect(target.textContent).not.toContain("Absence Categories");

    const saveBtn = [...target.querySelectorAll("button")].find((b) =>
      b.textContent.includes("Save"),
    );
    saveBtn?.click();
    await settle();

    const putCall = apiMock.mock.calls.find(
      ([path, opts]) => path === "/users/7" && opts?.method === "PUT",
    );
    expect(putCall).toBeTruthy();
    expect(putCall[1].body).not.toHaveProperty("category_ids");
    expect(putCall[1].body).not.toHaveProperty("absence_category_ids");
  });
});
