#!/usr/bin/env bash
# End-to-end test driver.
#
# Boots the full, production-like Docker stack (postgres with pg_tde, the
# Rust/Axum app, and the backup sidecar — exactly as start_local.sh does) under
# an isolated Compose project, waits until the API is reachable, runs the
# Playwright browser flow against it, then verifies the real backup/restore
# mechanism (e2e/backup-restore-check.sh), then always tears the stack down.
#
# One-time setup: cd e2e && npm install && npx playwright install chromium
#
# Usage:
#   ./e2e/run.sh
#
# Set ZERF_E2E_KEEP_UP=1 to leave the stack running after the test (for
# debugging / iterating on the test with `npx playwright test` directly).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT="zerf_e2e"
BASE_URL="http://localhost:3333"
ENV_FILE="$SCRIPT_DIR/.env.e2e"

# Two compose files: the base local stack, plus an overlay that gives the e2e
# stack its own volume/container names. Without the overlay, `down -v` would
# delete the same named volumes a real start_local.sh deployment uses.
compose() {
  docker compose -p "$PROJECT" --env-file "$ENV_FILE" \
    -f "$ROOT_DIR/docker/docker-compose-local.yml" \
    -f "$SCRIPT_DIR/docker-compose.e2e.yml" "$@"
}

cleanup() {
  local exit_code=$?
  if [ "${ZERF_E2E_KEEP_UP:-0}" = "1" ]; then
    echo "ZERF_E2E_KEEP_UP=1 — leaving the stack running at $BASE_URL" >&2
  else
    compose down -v --remove-orphans >/dev/null 2>&1 || true
    rm -f "$ENV_FILE"
  fi
  exit "$exit_code"
}
trap cleanup EXIT

umask 077
cat >"$ENV_FILE" <<EOF
# Generated by run.sh — ephemeral, for the e2e stack only. Do not commit.
ZERF_SESSION_SECRET=$(openssl rand -hex 32)
ZERF_POSTGRES_PASSWORD=$(openssl rand -hex 32)
ZERF_DB_ENCRYPTION_KEY=$(openssl rand -hex 32)
ZERF_POSTGRES_DB=zerf_e2e
ZERF_POSTGRES_USER=zerf_e2e
EOF

echo "Starting the production-like stack…"
compose up --build --wait --wait-timeout 420 -d

echo "Waiting for the API at $BASE_URL …"
ready=0
for _ in $(seq 1 60); do
  if curl -fsS "$BASE_URL/api/v1/settings/public" 2>/dev/null | grep -q ui_language; then
    ready=1
    break
  fi
  sleep 2
done
if [ "$ready" -ne 1 ]; then
  echo "API did not become ready in time." >&2
  compose logs --no-color
  exit 1
fi
echo "API is ready."

BASE_URL="$BASE_URL" npx --prefix "$SCRIPT_DIR" playwright test --config "$SCRIPT_DIR/playwright.config.js"

# The Playwright flow above has, by now, populated the database with real
# data through the app's own UI — exactly the kind of live state a backup
# needs to actually prove something about. Run the backup/restore check
# last so it operates on that populated database.
"$SCRIPT_DIR/backup-restore-check.sh" \
  zerf-e2e-postgres zerf-e2e-app zerf-e2e-backup zerf_e2e_backup_data \
  "$ENV_FILE" "$BASE_URL"
